version: '2'
services:
  web:
    image: nginx:alpine
    volumes:
     - .:/var/www/html:ro
     - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
     - "80:80"
    networks:
      appnet:
        ipv4_address: 178.18.0.10
  php:
    build: ./docker/php
    volumes:
     - .:/var/www/html
    ports:
     - "9000:9000"
    networks:
      appnet:
        ipv4_address: 178.18.0.20
  mongo:
    image: 'mongo:3.4.1'
    volumes:
      - data:/data/db:rw
      - data:/data/configdb:rw
    ports:
      - "27017:27017"
    networks:
      appnet:
        ipv4_address: 178.18.0.30
  smtp:
    image: mailhog/mailhog:latest
    ports:
     - "8025:8025"
    networks:
     - appnet
networks:
  appnet:
    driver: "bridge"
    ipam:
      driver: default
      config:
       - subnet: 178.18.0.0/16
volumes:
  data:
    driver: "local"
